name: Update Clash Nodes

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:


jobs:
  update:

    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:

      # 拉取仓库
      - name: Checkout
        uses: actions/checkout@v4


      # 下载节点页面
      - name: Download Wiki
        run: |

          curl -L \
          "https://raw.githubusercontent.com/wiki/Alvin9999-newpac/fanqiang/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7.md" \
          -o source.md



      # 提取节点
      - name: Extract nodes
        run: |

          grep -Eo \
          '(vmess|vless|trojan|ss|ssr|hysteria|hysteria2|tuic|anytls)://[^ "<>]+' \
          source.md \
          | sort -u \
          > nodes.txt



      # 下载 subconverter
      - name: Install subconverter

        run: |

          wget -q \
          https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz \
          -O subconverter.tar.gz


          tar -xzf subconverter.tar.gz


          chmod +x subconverter/subconverter



      # 启动 subconverter
      - name: Start subconverter

        run: |

          nohup ./subconverter/subconverter \
          > subconverter.log 2>&1 &


          sleep 3



      # 转换 Clash
      - name: Convert Clash Config

        run: |

          curl \
          "http://127.0.0.1:25500/sub?target=clash&url=data:text/plain;base64,$(base64 -w0 nodes.txt)&insert=false&emoji=true&scv=true" \
          -o clash.yaml



      # 检查
      - name: Check output

        run: |

          echo "节点数量:"
          grep "name:" clash.yaml | wc -l



      # 提交
      - name: Commit

        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"


          git add .


          git commit \
          -m "Update clash nodes" \
          || echo "No changes"


          git push
